from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    async def upload(self, key: str, content: bytes, content_type: str = "") -> str: ...
    async def download(self, key: str) -> bytes: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
